### ISSUE TITLE
How should I expect to use the args in my routes?

### ISSUE THREAD

**Issue by tookko** [blocknotes/kemal-rest-api#1]
Was testing with master branch, seems like posting to the endpoint passes the call to create() but args are always empty. What should I expect to put in my request body: JSON, form data, something else?

**Comment by blocknotes** [comment]
Hi @tookko
I updated the master branch.

Only formdata currently.
Test (using _basic.cr_ example):
`curl -X POST 'http://localhost:3000/items' --data 'name=Test&age=123'`
